# POST http://localhost:3000/person
# Content-Type: application/json

# {
#   "nome": "Carola",
#   "idade": 3,
#   "cor_favorita": "",
#   "numeros_da_sorte": ["01", "02", "03"]
# }




# GET http://localhost:3000/person
# Content-Type: application/json




# GET http://localhost:3000/person/6418dd1b3c92bc424792d8f5
# Content-Type: application/json




# PATCH http://localhost:3000/person/6418dd1b3c92bc424792d8f5
# Content-Type: application/json

# {
#         "_id": "64120e54256acefc557f29af",
#         "nome": "Bento",
#         "idade": 30,
#         "cor_favorita": "Amarelo",
#         "numeros_da_sorte": [
#             1,
#             2,
#             3
#         ]
# }




DELETE http://localhost:3000/person/64120e54256acefc557f29af
Content-Type: application/json



